import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout.js'
import styles from '../styles/Layout.module.css'

export default function Page() {
  const [articles, setArticles] = useState([])
  useEffect(() => {
    async function fetchData() {
      const response = await fetch('/api/articles')
      const articles = await response.json()
      setArticles(articles)
    }
    fetchData()
  }, [])
  return (
    <Layout>
      <Head>
        <title>MyStore - Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.centeredArticle}>
        <h1>
          MyStore Articles
        </h1>
        <p style={{fontStyle: 'italic'}}>Welcome Here, You can found all the articles of the Store<br></br></p>
        <ul>
          {articles.map( article => (
            <div className={styles.article_card}>
              <li key={article.slug} className={styles.article_content}>
                <h2 className={styles.article_title}><Link href={`/api/articles/${article.slug}`}>{article.title}</Link></h2>
                <p className={styles.article_description}>{article.description}</p>
                <p className={styles.article_price}>Price : {article.price}</p>
                <p className={styles.article_description}>Size : {article.size}</p>
              </li>
              <img width={140} src={article.urlArticle} alt={`Image de ${article.title}`} />
            </div>
          ))}
        </ul>
      </div>
    </Layout>
  )
}
