import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Contacts.module.css'
import Layout from '../components/Layout.js'

export default function Page() {
  return (
    <Layout>
      <Head>
        <title>MyStore - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Contact
        </h1>
        <form>
        <div>
          <label>
            <input type="text" name="firstname" class="form-input" placeholder="Your FirstName"/>
          </label>
        </div>
        <div>
          <label>
            <input type="text" name="lastname" class="form-input" placeholder="Your LastName"/>
          </label>
        </div>
        <div>
          <label>
            <input type="text" name="email" class="form-input" placeholder="Your Email"/>
          </label>
        <div>
        </div>
          <label>
            <textarea name="message" class="form-textarea" placeholder="Your Message"/>
          </label>
        </div>
        <div class="form-submit">
          <input type="submit" value="Send" class="form-input"/>
        </div>
      </form>
      </div>
      
      
      
    </Layout>
  )
}