// pages/[name]/index.js

import { useRouter } from 'next/router';
import Layout from '../components/Layout.js';
import Head from 'next/head'
import Link from 'next/link';
//import styles from '../styles/Layout.module.css'

function NamePage() {
  const router = useRouter();
  const { name } = router.query;

  // You can customize the content based on the 'name' parameter
  const content = getContentForName(name);

  return (
    <Layout>
      <Head>
        <title>MyStore - Hello pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="grid min-h-full place-items-center bg-whiteSpecial px-6 py-24 sm:py-32 lg:px-8">
        <div class="text-center">
          <p class="text-base font-semibold text-blueEce text-5xl">{content.title}</p>
          <h1 class="mt-4 text-3xl font-bold tracking-tight text-darkblue sm:text-3xl">{content.description}</h1>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <a href="/about" class="rounded-md bg-blueEce px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-darkblue focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Go back</a>
            <a href="/articles" class="text-sm font-semibold text-darkblue">See our Articles<span aria-hidden="true">&rarr;</span></a>
          </div>
        </div>
      </div>
    </Layout>
 
  );
}


function getContentForName(name) {
    switch (name) {
      case 'Elanore':
        return {
          title: 'Elanore\'s Page',
          description: 'Hello Guys, I am Elanore Lelievre, a 4th year student at the ECE school. I am 20 and I love node.js.',
        };
      case 'Noe':
        return {
          title: 'Noe\'s Page',
          description: 'Hello, my name is Noe. I am 20 years old, and I like playing video games and watching movies!',
        };
      case 'Solveig':
        return {
          title: 'Solveig\'s Page',
          description: 'I am Solveig Berling, also a 4th year student at ECE. I am 20 and I am fond WebTech',
        };
      case undefined :
        return {
          title: 'Not Found',
          description: 'No name provided.',
        };
      default:
        return {
          title: `Hello, ${name}!`,
          description: 'Happy to see you on our Website',
        };
    }
  }
  
export default NamePage;
