// pages/[name]/index.js
import { useRouter } from 'next/router';
import Layout from '../components/Layout.js';
import Head from 'next/head'
import Link from 'next/link';

function NamePage() {
  const router = useRouter();
  const { name } = router.query;
  // You can customize the content based on the 'name' parameter
  const content = getContentForName(name);
  return (
    <Layout>
      <Head>
        <title>MyStore - Hello pages</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid min-h-full place-items-center bg-whiteSpecial px-6 py-24 sm:py-32 lg:px-7">
        <div className="text-center">
          <p className="text-base font-semibold text-blueEce sm:text-3xl">{content.title}</p>
          <h1 className="mt-4 text-2xl font-bold tracking-tight text-darkblue sm:text-2xl">{content.description}</h1>
          <div className="mt-10 flex items-center justify-center gap-x-6">
            <Link href="/about" className="rounded-md bg-blueEce px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-darkblue focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Go back</Link>
            <Link href="/articles" className="text-sm font-semibold text-darkblue">See our Articles<span aria-hidden="true">&rarr;</span></Link>
          </div>
        </div>
      </div>
    </Layout>
 
  );
}


function getContentForName(name) {
  switch (name) {
    case 'Elanore':
      return {
        title: 'Elanore\'s Page',
        description: 'Hello Guys, I am Elanore Lelievre, a 4th year student at the ECE school. I am 20 and I love node.js.',
      };
    case 'Noe':
      return {
        title: 'Noe\'s Page',
        description: 'Hello, my name is Noe. I am 20 years old, and I like playing video games and watching movies!',
      };
    case 'Solveig':
      return {
        title: 'Solveig\'s Page',
        description: 'I am Solveig Berling, also a 4th year student at ECE. I am 20 and I am fond WebTech',
      };
    case undefined :
      return {
        title: 'Not Found',
        description: 'No name provided.',
      };
    default:
      return {
        title: `Hello, ${name}!`,
        description: 'Happy to see you on our Website',
      };
  }
}
  
export default NamePage;
