import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout.js'
//import styles from '../styles/Layout.module.css'

export default function Page() {
  return (
    <Layout>
      <Head>
        <title>MyStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <h1 className='wt-title text-darkblue'>
          Welcome to our Online<a href="https://github.com/Elanore1/ece-webtech-2023-fall-gr04-13">Web Store !</a>
          <br></br><br></br>
        </h1>
        <video height="300" width="300" autoPlay loop muted>
          <source src="/logoAnimated.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <ul>
          <li>
            <Link href="/articles">
              Our Clothes ➔
            </Link>
          </li>
          <li>
            <Link href="/about">
              About us ➔
            </Link>
          </li>
          <li>
            <Link href="/contacts">
              Contact us ➔
            </Link>
          </li>
        </ul>
      </div>
    </Layout>
  )
}