import Head from 'next/head'
import Layout from '../components/Layout.js'
import {useUser} from '../components/UserContext.js'
import { useRouter } from 'next/router'
import { supabaseClient } from '../components/supabaseClient'

export default function Page(){
    const {user} = useUser()
    const router = useRouter()

    const handleLogout = async ()=>{
        await supabaseClient.auth.signOut()
        router.push('/')
    }
    return (
        <Layout>
            <Head>
                <title>MyStore</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto container max-w-2xl md:w-3/4 shadow-md">
                <div className="bg-blueEce p-4 border-t-2 border-darkblue rounded-t">
                    <div className="max-w-sm mx-auto md:w-full md:mx-0">
                        <div className="inline-flex items-center space-x-4">
                            <img
                                className="w-10 h-10 object-cover rounded-full"
                                alt="User avatar"
                                src="https://avatars3.githubusercontent.com/u/72724639?s=400&u=964a4803693899ad66a9229db55953a3dbaad5c6&v=4"
                            />
                            <h1 className="text-white">Username</h1>
                        </div>
                    </div>
                </div>
                <div className="bg-white space-y-6">
                    <div className="md:inline-flex  space-y-4 md:space-y-0  w-full p-4 text-gray-500 items-center">
                        <h2 className="md:w-1/3 mx-auto max-w-sm">Account</h2>
                        <div className="md:w-2/3 mx-auto max-w-sm space-y-5">
                            <div>
                                <label className="text-sm text-gray-400">Username</label>
                                <div className="w-full inline-flex border">
                                    <div className="pt-2 w-1/12 bg-gray-100">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 text-gray-400 mx-auto">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.182 15.182a4.5 4.5 0 01-6.364 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zM9.75 9.75c0 .414-.168.75-.375.75S9 10.164 9 9.75 9.168 9 9.375 9s.375.336.375.75zm-.375 0h.008v.015h-.008V9.75zm5.625 0c0 .414-.168.75-.375.75s-.375-.336-.375-.75.168-.75.375-.75.375.336.375.75zm-.375 0h.008v.015h-.008V9.75z" />
                                    </svg>
                                    </div>
                                    <input type="text" className="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="myUsername" disabled/>
                                </div>
                            </div>
                            <div>
                                <label className="text-sm text-gray-400">Email</label>
                                <div className="w-full inline-flex border">
                                    <div className="pt-2 w-1/12 bg-gray-100 bg-opacity-50">
                                        <svg fill="none" className="w-6 text-gray-400 mx-auto" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
                                        </svg>
                                    </div>
                                    <input type="email" className="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="email@example.com" disabled/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div className="md:inline-flex  space-y-4 md:space-y-0  w-full p-4 text-gray-500 items-center">
                        <h2 className="md:w-1/3 mx-auto max-w-sm">Personal info</h2>
                        <div className="md:w-2/3 mx-auto max-w-sm space-y-5">
                            <div>
                                <label className="text-sm text-gray-400">First name</label>
                                <div className="w-full inline-flex border">
                                    <div className="w-1/12 pt-2 bg-gray-100">
                                        <svg
                                        fill="none"
                                        className="w-6 text-gray-400 mx-auto"
                                        viewBox="0 0 24 24"
                                        stroke="currentColor"
                                        >
                                        <path
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                            stroke-width="2"
                                            d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                                        />
                                        </svg>
                                    </div>
                                    <input type="text" className="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="Firstname" disabled/>
                                </div>
                            </div>
                            <div>
                                <label className="text-sm text-gray-400">Last name</label>
                                <div className="w-full inline-flex border">
                                    <div className="w-1/12 pt-2 bg-gray-100">
                                        <svg
                                        fill="none"
                                        className="w-6 text-gray-400 mx-auto"
                                        viewBox="0 0 24 24"
                                        stroke="currentColor"
                                        >
                                        <path
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                            stroke-width="2"
                                            d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                                        />
                                        </svg>
                                    </div>
                                    <input type="text" className="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="Lastname" disabled/>
                                </div>
                            </div>
                            <div>
                                <label className="text-sm text-gray-400">Phone number</label>
                                <div className="w-full inline-flex border">
                                    <div className="pt-2 w-1/12 bg-gray-100">
                                        <svg fill="none" className="w-6 text-gray-400 mx-auto" viewBox="0 0 24 24" stroke="currentColor" >
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"/>
                                        </svg>
                                    </div>
                                    <input type="text" className="w-11/12 focus:outline-none focus:text-gray-600 p-2" placeholder="06XXXXXXXX" disabled/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div className="md:inline-flex w-full space-y-4 md:space-y-0 p-8 text-gray-500 items-center">
                        <h2 className="md:w-4/12 max-w-sm mx-auto">Password</h2>
                        <div className="md:w-5/12 w-full md:pl-9 max-w-sm mx-auto space-y-5 md:inline-flex pl-2">
                            <div className="w-full inline-flex border-b">
                                <div className="w-1/12 pt-2">
                                    <svg fill="none" className="w-6 text-gray-400 mx-auto" viewBox="0 0 24 24" stroke="currentColor" >
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                                    </svg>
                                </div>
                                <input type="password" className="w-11/12 focus:outline-none focus:text-gray-600 p-2 ml-4" placeholder="Mypassword" disabled/>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div className="w-full p-4 text-right text-gray-500">
                        <button className="inline-flex items-center focus:outline-none mr-4">
                        <svg fill="none" className="w-4 mr-2" viewBox="0 0 24 24" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                        </svg>
                        Delete account
                        </button>
                        <button className="inline-flex items-center focus:outline-none mr-4" onClick={handleLogout}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 mr-2">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Logout
                        </button>
                    </div>
                </div>
            </div>
        </Layout>
    )
}