create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  firstname text,
  lastname text, 
  email text,
  subject text,
  message text
);

alter table public.contacts enable row level security;