import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../../components/Layout.js'
import { db } from '../api/articles.js'

export default function Page({
  article
}) {
  return (
    <Layout title={article.title} description="Generated by create next app">
      <h1 className='wt-title'>
        {article.title}
      </h1>
      <p> {article.price}</p>
      <p> {article.size}</p>
      <p> {article.description}</p>
    </Layout>
  )
}

export async function getStaticProps(ctx) {
  //const response = await fetch(`http://localhost:3000/api/articles/${ctx.params.slug}`)
  //const article = await response.json()
  const article = db.find(item => item.slug === `${ctx.params.slug}`)
  return {
    props: {
      article: article
    }
  };
}

export async function getStaticPaths(ctx) {
  //const response = await fetch(`http://localhost:3000/api/articles`)
  //const articles = await response.json()
  const paths = db.map(article =>({
    params: { slug: article.slug }
  }))
  return {
    paths: paths,
    fallback: false
  };
}