//database 
export const db = [{
  slug : 'Nike-Air-Force',
  title: 'Air Force',
  brand: 'Nike',
  hook: 'The charm continues with the Nike Air Force. This OG basketball shoe revisits its most famous elements!',
  description: ['Launched in 1982, the AF1 was the first basketball shoe to incorporate Nike Air technology. It revolutionized the sport and quickly became a worldwide success. Today, the Air Force 1 remains true to its roots, with the same soft, dynamic cushioning that changed sneaker history.',
    'Product details :',
    '- Foam midsole',
    '- Perforated toe',
    '- Rubber outsole'
  ],
  color: ['#000000','#FFFFFF'],
  size: ['37','38','39','40','41','42','43','44','45'],
  availability: 'In Stock',
  price: '$119,99',
  urlArticle: [
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dw08967115/images/hi-res/001227773_002.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dw15eb80f2/images/hi-res/001198486_002.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dw9a7f5e02/images/hi-res/001227773_003.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dwfb3b2ef2/images/hi-res/001198486_003.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
  ],
}, {
  slug : 'The-North-Face-Nuptse-Jacket',
  title: 'Nuptse Jacket',
  brand: 'The North Face',
  hook: 'Black down jacket with lined hood. Made of 100% nylon, warm lining, perfect for winter.',
  description: [`Inspired by the iconic 1996 Nuptse, this jacket makes a comeback with shiny fabric and 4 oversized shells featuring goose-down insulation. This voluminous 1996 Retro Nuptse Jacket will keep you warm and you'll certainly feel like you're in a 90s rap video.`,
    'Product details :',
    '- The North Face 1996 Retro Nuptse Jacket Summit Gold-TNF Black',
    '- Water-repellent fabric',
    '- Adjustable Velcro® tabs on cuffs',
    '- Hood stows in collar',
    '- Ripstop fabric with DWR water-repellent finish',
    '- Inside zipped pocket',
    '- Very dense, RDS-certified goose down',
  ],
  color: ['#000000','#8A2BE2','#FFFFFF','#FFFF00'],
  size: ['XS','S','M','L','XL','XXL'],
  price: '$329,99',
  availability: 'In Stock',
  urlArticle: ['https://www.cdiscount.com/pdt2/2/7/5/1/550x550/mp41730275/rw/veste-sans-manches-junior-the-north-face-retro-nup.jpg',
    'https://www.urbanexcess.com/cdn/shop/products/NF0A3C8DNL4_1_800x.jpg?v=1604920040',
    'https://i.ebayimg.com/images/g/1CAAAOSwpdtjm~Wv/s-l1200.jpg',
    'https://img.mytheresa.com/1094/1236/90/jpeg/catalog/product/bb/P00838303.jpg',
  ],
}, {
  slug : 'Carhartt-Banks-Beanie',
  title: 'Banks Beanie',
  brand: 'Carhartt',
  hook: 'The Banks beanie is made from 5-gauge stretch organic cotton knit. The short style features the Sports Label on the cuff.',
  description:  ['The beanie is crafted from a soft 4.6 mm wool-cashmere blend. Its rib-knit fabric ensures perfect comfort and fit. Adorned with a discreet woven label on the lapel. One size fits all.',
    'Product details :',
    '- Height: 16 cm / 6.3 inch',
    '- 100% organic cotton',
    '- 5 gauge',
    '- Sports Label',
  ],
  color: ['#596643','#d1af76','#5d5d5d'],
  size: ['One Size'],
  price: '$35,00',
  availability: 'In Stock',
  urlArticle: ['https://i1.adis.ws/i/carhartt_wip/I032220_1ND_XX-ST-01/banks-beanie-smoke-green-1198.png?$pdp_02$',
    'https://www.montaz.com/cache/imgcatalogue/2023-2024/800x800/sl/carhartt-wip-banks-beanie-leather.jpg',
    'https://www.montaz.com/cache/imgcatalogue/2023-2024/800x800/sl/carhartt-wip-banks-beanie-mirror.jpg',
  ],
}, {
  slug : 'Tee-Shirt-Nike',
  title: 'Tee-Shirt Club',
  brand: 'Nike',
  hook: 'Nike is back with a new version of its iconic Club Tee Shirt. Its loose fit around the body and hips offers absolute comfort right from the first slip-on.',
  description: [`Nike unveils its textile collection with the Nike Tee Shirt Club. It features a straight cut, a solid yellow hue, and the brand's emblematic logo on the chest. Perfect for both indoor and outdoor wear, it's a wardrobe classic.`,
    'Product details :',
    '- 100% cotton',
    '- embroidered logo',
    '- unisex ',
    '- long sleeve ',
  ],
  color: ['#8A2BE2','#0e254a','#FFFFFF','#FFFF00'],
  size: ['XS','S','M','L','XL','XXL'],
  price: '$25,00',
  availability: 'In Stock',
  urlArticle: ['https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dwde24c6b9/images/hi-res/001513745_104.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dwc62c7e0b/images/hi-res/001466114_104.png?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dwbab3c230/images/hi-res/001513741_104.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
    'https://www.courir.com/dw/image/v2/BCCL_PRD/on/demandware.static/-/Sites-master-catalog-courir/default/dw2a600f1e/images/hi-res/001509883_104.jpg?sw=600&sh=600&sm=fit&q=90&frz-v=38',
  ],
}, {
  slug : 'New-Balance-Hoodie',
  title: 'Hoodie',
  brand: 'New Balance',
  hook: 'Go for casual style with the New Balance NB Small Logo hoodie. Made from soft cotton for unrivalled comfort. Its classic green design is enhanced by the embossed logo.',
  description: ['Composition :',
    '- 36% Polyester',
    '- 64% Better Cotton',
    'Product details :',
    '- Cut: Relaxed fit',
    '- Sleeve: Long sleeve  Hood: With hood  Pockets: Side pockets',
    '- Closure: Sweater',
    '- Bottom hem: Elastic',
    '- Details: Printed front, Printed hood,Printed Logo',
  ],
  color: ['#2e7d32','#d1af76','#000000'],
  size: ['XS','S','M','L','XL','XXL'],
  price: '$65,99',
  availability: 'In Stock',
  urlArticle: [
    'https://www.cdiscount.com/pdt2/8/0/3/2/700x700/mp60335803/rw/sweat-a-capuche-avec-logo-central-new-balance-pour.jpg',
    'https://static.footshop.com/img/p/8/3/2/4/5/3/832453-full_product.jpg',
    'https://static.footshop.com/img/p/8/3/2/4/3/8/832438.jpg',
  ],
}, {  
  slug : 'H&M-Regular-Cargo-Pants',
  title: 'Regular Fit Cargo Pants 2715',
  brand: 'H&M',
  hook: 'New LBO 2023 collection. White urban cargo pants in stretch cotton. Front pockets, drawcord, wide fit.',
  description: ['Model 2715.Regular fit. This product has a wide fit.Urban cargo pants in stretch cotton',
    'Composition :',
    '- 98% Cotton',
    '- 2% Elastane',
    'Product details :',
    '- Front pockets',
    '- Cargo pockets',
    '- Drawcord',
    '- Elastic waistband and ankle support',
  ],
  color: ['#FFFFFF','#000000','#d1af76','#596643'],
  size: ['XS','S','M','L','XL','XXL'],
  price: '$56,99',
  availability: 'In Stock',
  urlArticle: ['https://assets.laboutiqueofficielle.com/w_1100,q_auto,f_auto/media/products/2022/07/27/lbo_330635_SHALBO-2715_20221014T082015_01.jpg',
    'https://assets.laboutiqueofficielle.com/w_1100,q_auto,f_auto/media/products/2022/10/12/lbo_344427_LBO_1070318-0219_20230106T124500_03.jpg',
    'https://assets.laboutiqueofficielle.com/w_1100,q_auto,f_auto/media/products/2022/07/27/lbo_330632_SHALBO-2712_20220914T160223_05.jpg',
    'https://assets.laboutiqueofficielle.com/w_1100,q_auto,f_auto/media/products/2018/07/18/jack-and-jones_148187_12141844_OLIVE-NIGHT_20180720T111815_01.jpg',
  ],
}, {
  slug : 'LBO-Banana-Bag-Rabbit',
  title: 'Banana Bag Rabbit',
  brand: 'LBO',
  hook: 'New Collection Sale Môme 2023. Lapin graffiti model, metal zipper closure and adjustable strap with clip.',
  description: ['Rabbit graffiti model',
    'Composition :',
    '- 100% Polyester',
    '- 2% Elastane',
    'Product details :',
    '- Exclusive',
    '- Banana bag with Sale Môme visual print',
    '- Metal zip closure',
    '- Zipped back pocket',
    '- Adjustable shoulder strap with clip',
  ],
  color: ['#000000'],
  size: ['One Size'],
  price: '$19,99',
  availability: 'In Stock',
  urlArticle: ['https://assets.laboutiqueofficielle.com/w_450,q_auto,f_auto/media/products/2023/07/20/niro_380165_SALEMOME_SACB_LAPINGRAFFITI_NOIROS_20230725T152435_01.jpg',
    'https://assets.laboutiqueofficielle.com/w_450,q_auto,f_auto/media/products/2023/07/20/niro_380165_SALEMOME_SACB_LAPINGRAFFITI_NOIROS_20230725T152437_02.jpg',
    'https://assets.laboutiqueofficielle.com/w_450,q_auto,f_auto/media/products/2023/07/20/niro_380165_SALEMOME_SACB_LAPINGRAFFITI_NOIROS_20230725T152438_03.jpg',
    'https://assets.laboutiqueofficielle.com/w_450,q_auto,f_auto/media/products/2023/07/20/niro_380165_SALEMOME_SACB_LAPINGRAFFITI_NOIROS_20230725T152439_04.jpg',
  ],
}, {
  slug : 'SocksParty-Mr-Mrs-Socks',
  title: 'Mr.Mrs. Socks',
  brand: 'SocksParty',
  hook: 'Monsieur Madame x Label Chaussette: the famous series written and designed by Roger Hargreaves is now on your feet! Blue Stripes',
  description: [`Are you a "Mrs. Late" or a "Mr. Curious"? Now you can find the whole family on your socks! These socks include a good part of the "Monsieur Madame" family. They're made locally, in the Limousin region of France.`,
    'Composition :',
    '- 87% Cotton',
    '- 12% Polyamide',
    '- 1% Elastane',
  ],
  color: ['#1976d2','#FFFFFF'],
  size: ['34-38','38-42','42-46'],
  price: '$19,00',
  availability: 'In Stock',
  urlArticle: ['https://www.label-chaussette.com/cdn/shop/products/Rayee-bleu-Monsieur-Madame-x-Label-Chaussette_1000x.jpg?v=1638289732',
    'https://www.lepetitlocal.fr/6605-large_default/chaussettes-monsieur-madame-blanches-label-chaussette.jpg',
    'https://www.lepetitlocal.fr/7226-large_default/chaussettes-monsieur-madame-bleu-label-chaussette.jpg',
    'https://www.lepetitlocal.fr/6607-large_default/chaussettes-monsieur-madame-blanches-label-chaussette.jpg',
  ],
}
]

export default function handler(req, res) {
  res.status(200).json(db)
}
